[package]
name = "pinned-mutex"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "0.12", optional = true }

[dev-dependencies]
pin-project = "1.1"
